# Generated by Django 3.0.6 on 2020-06-27 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=64, unique=True, verbose_name='账单号')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('power_comsumption', models.FloatField(verbose_name='用电总度数')),
                ('fee', models.FloatField(verbose_name='总费用')),
            ],
        ),
        migrations.CreateModel(
            name='CentralAirConditioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_state', models.CharField(choices=[('close', '关闭'), ('set_Model', '设置模式'), ('ready', '就绪'), ('none', '备用')], default='close', max_length=64, verbose_name='中央空调状态')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('temp_highlimit', models.IntegerField(verbose_name='温控范围最高温')),
                ('temp_lowlimit', models.IntegerField(verbose_name='温控范围最低温')),
                ('default_temp', models.IntegerField(verbose_name='缺省温度')),
                ('feerate_H', models.FloatField(verbose_name='高风费率')),
                ('feerate_M', models.FloatField(verbose_name='中风费率')),
                ('feerate_L', models.FloatField(verbose_name='低风费率')),
            ],
        ),
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=2, verbose_name='送风模式')),
                ('start_time', models.DateTimeField(verbose_name='开始服务时间')),
                ('end_time', models.DateTimeField(verbose_name='结束服务时间')),
                ('fee_duration', models.FloatField(verbose_name='服务时长(分钟)')),
                ('request_time', models.DateTimeField(verbose_name='发送请求时间')),
                ('end_request_time', models.DateTimeField(verbose_name='停止请求时间')),
                ('request_num', models.IntegerField(verbose_name='发送请求次数')),
                ('first_temp', models.IntegerField(verbose_name='初始温度')),
                ('target_temp', models.IntegerField(verbose_name='目标温度')),
                ('power_comsumption', models.FloatField(verbose_name='用电度数')),
                ('fee', models.FloatField(verbose_name='费用')),
                ('day_power_comsumption', models.FloatField(verbose_name='每日总用电度数')),
                ('day_fee', models.FloatField(verbose_name='每日空调总费用')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=64, unique=True, verbose_name='详单号')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=2, verbose_name='送风模式')),
                ('fee_rate', models.FloatField(verbose_name='费率')),
                ('fee_duration', models.FloatField(verbose_name='服务时长(分钟)')),
                ('power_comsumption', models.FloatField(verbose_name='用电度数')),
                ('fee', models.FloatField(verbose_name='总费用')),
            ],
        ),
        migrations.CreateModel(
            name='FrontWaiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('date_in', models.DateField(verbose_name='入住日期')),
                ('date_out', models.DateField(verbose_name='登出日期')),
            ],
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=2, verbose_name='送风模式')),
                ('start_time', models.DateTimeField(verbose_name='开始服务时间')),
                ('end_time', models.DateTimeField(verbose_name='结束服务时间')),
                ('fee_duration', models.FloatField(verbose_name='服务时长(分钟)')),
                ('request_time', models.DateTimeField(verbose_name='发送请求时间')),
                ('end_request_time', models.DateTimeField(verbose_name='停止请求时间')),
                ('request_num', models.IntegerField(verbose_name='发送请求次数')),
                ('first_temp', models.IntegerField(verbose_name='初始温度')),
                ('target_temp', models.IntegerField(verbose_name='目标温度')),
                ('power_comsumption', models.FloatField(verbose_name='用电度数')),
                ('fee', models.FloatField(verbose_name='费用')),
                ('daily_power_comsumption', models.FloatField(verbose_name='每日总用电度数')),
                ('daily_fee', models.FloatField(verbose_name='每日空调总费用')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=64, unique=True, verbose_name='服务队列号')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=2, verbose_name='送风模式')),
                ('request_time', models.DateTimeField(verbose_name='发送请求时间')),
                ('current_temp', models.IntegerField(verbose_name='当前温度')),
                ('target_temp', models.IntegerField(verbose_name='目标温度')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='房间号')),
                ('room_state', models.SmallIntegerField(choices=[(0, '关闭'), (1, '运行'), (2, '挂起')], default=0, max_length=64, verbose_name='房间从控机状态')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=1, verbose_name='送风模式')),
                ('current_temp', models.IntegerField(verbose_name='当前温度')),
                ('target_temp', models.IntegerField(verbose_name='目标温度')),
                ('fee_rate', models.FloatField(verbose_name='费率')),
                ('fee', models.FloatField(verbose_name='总费用')),
                ('duration', models.IntegerField(verbose_name='服务时长(秒)')),
            ],
        ),
        migrations.CreateModel(
            name='ServeQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=64, unique=True, verbose_name='服务队列号')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=2, verbose_name='送风模式')),
                ('start_time', models.DateTimeField(verbose_name='开始服务时间')),
                ('end_time', models.DateTimeField(verbose_name='结束服务时间')),
                ('fee_duration', models.FloatField(verbose_name='服务时长(分钟)')),
                ('fee_rate', models.FloatField(verbose_name='费率')),
                ('power_comsumption', models.FloatField(verbose_name='用电度数')),
                ('fee', models.FloatField(verbose_name='费用')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('room_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='房间号')),
                ('init_temp', models.FloatField(verbose_name='初始温度')),
                ('current_temp', models.FloatField(verbose_name='当前温度')),
                ('last_update', models.TimeField(default=datetime.datetime(2020, 6, 27, 1, 57, 7, 45289, tzinfo=utc), verbose_name='上次更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=64, verbose_name='房客编号')),
                ('room_id', models.CharField(max_length=64, verbose_name='房间号')),
                ('temp_mode', models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=0, verbose_name='制冷制热模式')),
                ('blow_mode', models.SmallIntegerField(choices=[(0, '低风'), (1, '中风'), (2, '高风')], default=2, verbose_name='送风模式')),
                ('start_time', models.DateTimeField(verbose_name='开始服务时间')),
                ('end_time', models.DateTimeField(verbose_name='结束服务时间')),
                ('fee_duration', models.FloatField(verbose_name='服务时长(分钟)')),
                ('request_time', models.DateTimeField(verbose_name='发送请求时间')),
                ('end_request_time', models.DateTimeField(verbose_name='停止请求时间')),
                ('request_num', models.IntegerField(verbose_name='发送请求次数')),
                ('first_temp', models.IntegerField(verbose_name='初始温度')),
                ('target_temp', models.IntegerField(verbose_name='目标温度')),
                ('power_comsumption', models.FloatField(verbose_name='用电度数')),
                ('fee', models.FloatField(verbose_name='费用')),
                ('week_power_comsumption', models.FloatField(verbose_name='每日总用电度数')),
                ('week_fee', models.FloatField(verbose_name='每日空调总费用')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
