# Generated by Django 3.0.4 on 2020-06-27 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 11, 4, 51, 434549), verbose_name='上次更新时间'),
        ),
    ]
