# Generated by Django 3.0.6 on 2020-06-27 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 1, 58, 6, 962493, tzinfo=utc), verbose_name='上次更新时间'),
        ),
    ]
