# Generated by Django 3.0.6 on 2020-06-27 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='guest_id',
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 18, 12, 28, 388443), verbose_name='上次更新时间'),
        ),
    ]
