# Generated by Django 3.0.6 on 2020-06-27 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrecord',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 21, 40, 36, 287168), verbose_name='上次更新时间'),
        ),
    ]
