# Generated by Django 3.0.4 on 2020-06-27 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200627_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 11, 36, 5, 771964), verbose_name='上次更新时间'),
        ),
    ]
