# Generated by Django 3.0.6 on 2020-06-27 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200627_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_state',
            field=models.SmallIntegerField(choices=[(0, '关闭'), (1, '运行'), (2, '挂起')], default=0, verbose_name='房间从控机状态'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 2, 0, 7, 622504, tzinfo=utc), verbose_name='上次更新时间'),
        ),
    ]
