# Generated by Django 3.0.6 on 2020-06-27 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200627_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='RR_id',
            new_name='RR',
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 21, 41, 47, 433165), verbose_name='上次更新时间'),
        ),
    ]
