# Generated by Django 3.0.6 on 2020-06-27 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200627_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrecord',
            name='blow_mode',
        ),
        migrations.AddField(
            model_name='requestrecord',
            name='temp_mode',
            field=models.SmallIntegerField(choices=[(1, '制冷模式'), (-1, '制热模式')], default=2, verbose_name='送风模式'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 27, 22, 18, 26, 811681), verbose_name='上次更新时间'),
        ),
    ]
