# Generated by Django 3.0.6 on 2020-06-28 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200627_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrecord',
            name='request_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2020, 6, 28, 1, 48, 6, 678482), verbose_name='上次更新时间'),
        ),
    ]
